##########################################
## !!! 示例配置，修改无效 !!!
## !!! example config, modify invalid !!!
##########################################
application:

  # 程序配置（可选）
  # ！以下为默认值，如非了解不建议修改
  config:
    expected_quantity: 2000000  #预期规则数量
    fault_tolerance: 0.001 #容错率
    warn_limit: 6 #警告阈值, 原始规则长度小于该值时会输出警告日志

    # 域名检测，启用时将进行解析以验证域名有效性
    # ！开启此功能可能导致处理时间大幅延长
    # ！仅支持特定规则，具体原因请查看项目主页说明
    domain-detect:
      enable: false   # 是否启用
      timeout: 3000   # 查询超时（毫秒）
      concurrency: 10 # 并发查询数
      provider:       # 使用的 DNS 服务器，仅支持 IP，多个之间具备优先级; 为空则使用默认DNS
        - 223.5.5.5
        - 8.8.8.8

    # 排除指定内容
    # 在解析结束后，规则内容命中此列表将直接认定为无效


  # 规则源配置
  # remote为远程规则，local为本地规则，支持多个规则源
  rule:
    #远程订阅规则 （！使用前请删除下方示例配置, 注意缩进）
    remote:
      - name: '秋风规则（联盟sdk）'               #可选参数: 规则名称，如无将使用 path 作为名称
        path: 'https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-hosts.txt' #必要参数: 规则url，仅支持 http/https，不限定响应内容格式
        type: hosts                       #可选参数: 规则类型：easylist (默认)、dnsmasq、clash、smartdns、hosts

      - name: 'hagezi（一加/oppo系统）'
        path: 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/hosts/native.oppo-realme.txt'
        type: hosts

      - name: '217heidai（地理域名为中国的域名）'
        path: 'https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockhostslite.txt'
        type: hosts
  
      - name: 'qq5460168（国内规则聚合）'
        path: 'https://raw.githubusercontent.com/qq5460168/666/refs/heads/master/hosts.txt'
        type: hosts

      - name: 'lingeringsound'
        path: 'https://raw.githubusercontent.com/lingeringsound/10007/main/reward'
        type: hosts

  #输出配置
  output:
    #文件头配置，将自动作为注释添加至每个规则文件开始
    #可使用占位符 ${name}、${type}、${desc} 以及 ${date} (当前日期)
    file_header: |
      ADFS AdBlock ${type}
      Last Modified: ${date}
      Homepage: https://github.com/fordes123/ad-filters-subscriber/

    #输出规则文件列表 （！注意缩进，且每个类型只能输出一个文件）
    files:
      - name: hosts.txt
        type: hosts
